# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: db:v2
    container_name: db
    build:
      context: .
      dockerfile: ./docker/dockerfile.database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  api:
    image: api:v2
    container_name: api
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
  ui:
    image: ui:v2
    container_name: ui
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "4000:80"